name: Build and Publish Docker Image

on:
  push:
    branches: [main]

jobs:
  build-and-push:
    name: Build Docker image and push to repository
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push
        uses: docker/build-push-action@v2
        with:
          context: .
          tags: |
            kazemakase/wasserstand:latest
          push: true

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
