name: Register flows with prefect

on:
  push:
    branches: [main]

jobs:
  register-flows:
    name: Register flows with prefect
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Prepare Environment
        run: pip3 install .

      - name: Log in to prefect
        run: prefect auth login --key ${{ secrets.PREFECT_CLOUD_KEY }}

      - name: "Register all cloud flows"
        run: for X in flows/*_cloud.py; do PYTHONPATH=. prefect register -p $X --project Wasserstand; done
